# -*- coding: utf-8 -*-
"""PPTassignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BCbkPpWXmsqKH8iFNO3zjYPeZ1IPSr1u

<aside>
💡 **Q1.** Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

**Example:**
Input: nums = [2,7,11,15], target = 9
Output0 [0,1]

**Explanation:** Because nums[0] + nums[1] == 9, we return [0, 1][

</aside>
"""

def  two_sum(nums,target):
  num_indices={}
  for i, num in enumerate(nums):
    complement=target-num


    if complement in num_indices:
      return[num_indices[complement],1]

    num_indices[num]=1

  return[]

nums=[2,7,11,15]
target=9

result = two_sum(nums,target)
print(result)

"""<aside>
💡 **Q2.** Given an integer array nums and an integer val, remove all occurrences of val in nums in-place. The order of the elements may be changed. Then return the number of elements in nums which are not equal to val.

Consider the number of elements in nums which are not equal to val be k, to get accepted, you need to do the following things:

- Change the array nums such that the first k elements of nums contain the elements which are not equal to val. The remaining elements of nums are not important as well as the size of nums.
- Return k.

**Example :**
Input: nums = [3,2,2,3], val = 3
Output: 2, nums = [2,2,_*,_*]

**Explanation:** Your function should return k = 2, with the first two elements of nums being 2. It does not matter what you leave beyond the returned k (hence they are underscores)[

</aside>
"""

def removeElement(nums,val):
  left=0
  right=len(nums)-1

  while left<=right:
    if nums[right]==val:
      right-=1
    else:
      nums[left]=nums[right]
      left +=1
      right -=1
  return left

nums=[3, 2, 2, 3]
val=3
result=removeElement(nums,val)
print(result)
print(nums)

"""<aside>
💡 **Q3.** Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity.

**Example 1:**
Input: nums = [1,3,5,6], target = 5

Output: 2

</aside>
"""

def searchInsert(nums,target):
    left = 0
    right = len(nums)-1
    
    while left<=right:
      mid=left+(right-left)//2

      if nums[mid]==target:
        return mid 
      elif nums[mid]<target:
        left=mid+1
      else:
        right=mid-1

    return left




nums=[1,3,5,6]
target=5

index= searchInsert(nums,target)
print(index)

"""<aside>
💡 **Q4.** You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.

Increment the large integer by one and return the resulting array of digits.

**Example 1:**
Input: digits = [1,2,3]
Output: [1,2,4]

**Explanation:** The array represents the integer 123.

Incrementing by one gives 123 + 1 = 124.
Thus, the result should be [1,2,4].

</aside>
"""

def plusOne(digits):
  n=len(digits)

  for i in range(n - 1, -1, -1):
    if digits[i]!=9:
      digits[i]+=1
      return digits

    digits[i]=0
  digits.insert(0,1)

  return digits

digits=[1,2,3] 
result= plusOne(digits)
print(result)

"""<aside>
💡 **Q5.** You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.

Merge nums1 and nums2 into a single array sorted in non-decreasing order.

The final sorted array should not be returned by the function, but instead be stored inside the array nums1. To accommodate this, nums1 has a length of m + n, where the first m elements denote the elements that should be merged, and the last n elements are set to 0 and should be ignored. nums2 has a length of n.

**Example 1:**
Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
Output: [1,2,2,3,5,6]

**Explanation:** The arrays we are merging are [1,2,3] and [2,5,6].
The result of the merge is [1,2,2,3,5,6] with the underlined elements coming from nums1.

</aside>
"""

def merge(nums1,m,nums2,n):
  ptr1=m-1
  ptr2=n-1
  current=m+n-1


  while ptr1>=0 and ptr2>=0:
    if nums1[ptr1]>nums2[ptr2]:
      nums1[current]=nums1[ptr1]
      ptr1-=1

    else:
      nums1[current]=nums2[ptr2]
      ptr2-=1
    current-=1


nums1=[1,2,3,0,0,0]
m=3
nums2=[2,5,6]
n=3
merge(nums1,m,nums2,n)
print(nums1)

"""<aside>
💡 **Q6.** Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.

**Example 1:**
Input: nums = [1,2,3,1]

Output: true

</aside>
"""

def containDuplicate(nums):
    seen=set()
    for num in nums:
      if num in seen:
        return True
      seen.add(num)
    return False

nums = [1,2,3,1]
output=containDuplicate(nums)
print(output)

"""<aside>
💡 **Q7.** Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the nonzero elements.

Note that you must do this in-place without making a copy of the array.

**Example 1:**
Input: nums = [0,1,0,3,12]
Output: [1,3,12,0,0]

</aside>
"""

def moveZeros(nums):
    writePtr=0


    for readPtr in range(len(nums)):
        if nums[readPtr]!=0:
          nums[writePtr]=nums[readPtr]
          writePtr += 1

    while writePtr<len(nums):
       nums[writePtr]=0
       writePtr += 1

    return nums 


nums = [0,1,0,3,12]
result=moveZeros(nums)
print(result)

"""<aside>
💡 **Q8.** You have a set of integers s, which originally contains all the numbers from 1 to n. Unfortunately, due to some error, one of the numbers in s got duplicated to another number in the set, which results in repetition of one number and loss of another number.

You are given an integer array nums representing the data status of this set after the error.

Find the number that occurs twice and the number that is missing and return them in the form of an array.

**Example 1:**
Input: nums = [1,2,2,4]
Output: [2,3]

</aside>
"""

def findErrorNums(nums):
  count={}
      
  for num in nums:
    if num not in count:
      count[num]=1
    else:
      count[num]+=1
  
  duplicate=missing=0
  n=len(nums)
  for i in range(1,n+1):
        if i not in count:
          missing=i
        elif count[i]==2:
          duplicate=i

  
  return[duplicate,missing]

nums=[1,2,2,4]
result=findErrorNums(nums)
print(result)

